### ISSUE TITLE
Error in addition 

### ISSUE THREAD

**Issue by vik17ag** [Gperez88/CalculatorInputView#8]
Hi,

When i do continuous operations like (x) and then (+) , the value is not correct

Pls check the photo attached

![device-2017-02-25-190352](https://cloud.githubusercontent.com/assets/14138472/23331494/2c5acaec-fb8d-11e6-913b-cba6b46a815c.png)

**Comment by Gperez88** [comment]
we'll work on that.

**Comment by Gperez88** [comment]
done in version 1.0.2
